name: Train Model on Data Change

on:
  push:
    branches:
      - main
    paths:
      - 'artifacts/properties.csv'  # Runs when dataset changes
      - 'src/**'     # Runs when code changes
      - '.github/workflows/train.yml'

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.0"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install ipykernel  # Install ipykernel for Jupyter kernel
          python -m ipykernel install --user --name=python3 --display-name "Python 3"  # Register the kernel

      - name: Train Model
        run: |
          python src/pipeline/train_pipeline.py  # Your training script

      - name: Run tests
        run: |
          pytest
      
      - name: Save Model Artifacts
        run: |
          mkdir -p artifacts/
          git add artifacts/preprocessor.pkl
          git add artifacts/scaler_y.pkl
          git add artifacts/model.pkl

      - name: Commit and Push New Model
        run: |
          git config --global user.email "gmnaik96@gmail.com"
          git config --global user.name "gmnaik"
          git add artifacts/model.pkl
          git commit -m "Auto-update trained model [skip ci]" || echo "No changes to commit"
          git push
          