name: Train Model on Data Change

on:
  push:
    branches:
      - main
    paths:
      - 'artifacts/properties.csv'  # Runs when dataset changes
      - 'src/**'     # Runs when code changes
      - '.github/workflows/train.yml'

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.0"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install ipykernel  # Install ipykernel for Jupyter kernel
          python -m ipykernel install --user --name=python3 --display-name "Python 3"  # Register the kernel

      - name: Train Model
        run: |
          python src/pipeline/train_pipeline.py  # Your training script

      #- name: Run tests
        #run: |
          #pytest
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: artifacts/

      - name: Add, Commit And Push New Model
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add artifacts/
          git commit -m "Add model and preprocessing files"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/gmnaik/housepriceprediction.git
          