name: Train Model on Data Change

on:
  push:
    branches:
      - main
    paths:
      - 'artifacts/properties.csv'  # Runs when dataset changes
      - 'src/**'     # Runs when code changes
      - '.github/workflows/train.yml'

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.0"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install ipykernel  # Install ipykernel for Jupyter kernel
          python -m ipykernel install --user --name=python3 --display-name "Python 3"  # Register the kernel

      - name: Train Model
        run: |
          python src/pipeline/train_pipeline.py  # Your training script
      